package dev.kolektiv.keel.typegen

import dev.kolektiv.keel.action.ActionRegistry
import dev.kolektiv.keel.page.PageRegistry
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.descriptors.SerialKind
import kotlinx.serialization.descriptors.StructureKind

/**
 * Walks [PageRegistry] serializers and emits TypeScript interfaces.
 *
 * Supported: data classes, lists, maps, primitives, nullable, enums.
 * Sealed polymorphism and contextual serializers are out of scope.
 */
object Typegen {
    fun emit(
        pages: PageRegistry,
        actions: ActionRegistry = ActionRegistry(),
        pagesName: String = "Pages",
    ): String = emit(TypegenContract(pages.pages, actions.actions), pagesName)

    fun emit(
        contract: TypegenContract,
        pagesName: String = "Pages",
    ): String = Emitter(contract, pagesName).emit()
}

private class Emitter(
    private val contract: TypegenContract,
    private val pagesName: String,
) {
    private val named = LinkedHashMap<String, SerialDescriptor>()
    private val aliases = LinkedHashMap<String, String>()
    private val usedNames = mutableSetOf<String>()
    private val visiting = mutableSetOf<String>()

    fun emit(): String {
        for (binding in contract.pages) {
            collect(binding.serializer.descriptor)
        }
        for (binding in contract.actions) {
            collect(binding.input.descriptor)
            collect(binding.output.descriptor)
        }
        for (serializer in contract.types) {
            collect(serializer.descriptor)
        }
        val pageIdName = pageIdName(pagesName)
        val actionsName = actionsName(pagesName)
        val actionIdName = actionIdName(pagesName)
        return buildString {
            appendLine("// Generated by dev.kolektiv.keel.typegen.Typegen. Do not edit.")
            appendLine()
            for ((_, descriptor) in named) {
                val name = aliases.getValue(serialKey(descriptor))
                when (descriptor.kind) {
                    SerialKind.ENUM -> {
                        val values = (0 until descriptor.elementsCount).joinToString(" | ") { i ->
                            "\"${descriptor.getElementName(i)}\""
                        }
                        appendLine("export type $name = $values")
                        appendLine()
                    }
                    else -> {
                        appendLine("export interface $name {")
                        for (i in 0 until descriptor.elementsCount) {
                            val field = descriptor.getElementName(i)
                            val type = tsType(descriptor.getElementDescriptor(i))
                            appendLine("  $field: $type")
                        }
                        appendLine("}")
                        appendLine()
                    }
                }
            }
            appendLine("export interface $pagesName {")
            for (binding in contract.pages) {
                appendLine("  \"${binding.id}\": ${tsType(binding.serializer.descriptor)}")
            }
            appendLine("}")
            appendLine()
            appendLine("export type $pageIdName = keyof $pagesName")
            if (contract.actions.isNotEmpty()) {
                appendLine()
                appendLine("export interface $actionsName {")
                for (binding in contract.actions) {
                    val input = tsType(binding.input.descriptor)
                    val output = tsType(binding.output.descriptor)
                    appendLine("  \"${binding.id}\": { in: $input; out: $output }")
                }
                appendLine("}")
                appendLine()
                appendLine("export type $actionIdName = keyof $actionsName")
            }
        }
    }

    private fun collect(descriptor: SerialDescriptor) {
        when (descriptor.kind) {
            StructureKind.LIST -> collect(descriptor.getElementDescriptor(0))
            StructureKind.MAP -> {
                collect(descriptor.getElementDescriptor(0))
                collect(descriptor.getElementDescriptor(1))
            }
            SerialKind.ENUM -> remember(descriptor)
            StructureKind.CLASS, StructureKind.OBJECT -> {
                if (descriptor.isInline && descriptor.elementsCount == 1) {
                    collect(descriptor.getElementDescriptor(0))
                    return
                }
                val key = serialKey(descriptor)
                if (isKotlinBuiltin(key)) return
                if (key in named || key in visiting) return
                visiting.add(key)
                for (i in 0 until descriptor.elementsCount) {
                    collect(descriptor.getElementDescriptor(i))
                }
                visiting.remove(key)
                remember(descriptor)
            }
            else -> Unit
        }
    }

    private fun remember(descriptor: SerialDescriptor) {
        val key = serialKey(descriptor)
        if (key in aliases) return
        aliases[key] = uniqueName(key)
        named[key] = descriptor
    }

    private fun uniqueName(serialName: String): String {
        val simple = simpleName(serialName)
        if (usedNames.add(simple)) return simple
        val qualified = serialName.replace('.', '_')
        var candidate = qualified
        var n = 2
        while (!usedNames.add(candidate)) {
            candidate = "${qualified}_$n"
            n += 1
        }
        return candidate
    }

    private fun tsType(descriptor: SerialDescriptor): String {
        val inner = when (descriptor.kind) {
            PrimitiveKind.BOOLEAN -> "boolean"
            PrimitiveKind.CHAR, PrimitiveKind.STRING -> "string"
            PrimitiveKind.BYTE, PrimitiveKind.SHORT, PrimitiveKind.INT,
            PrimitiveKind.LONG, PrimitiveKind.FLOAT, PrimitiveKind.DOUBLE,
            -> "number"
            StructureKind.LIST -> "${tsType(descriptor.getElementDescriptor(0))}[]"
            StructureKind.MAP -> {
                val key = tsType(descriptor.getElementDescriptor(0))
                val value = tsType(descriptor.getElementDescriptor(1))
                "Record<$key, $value>"
            }
            SerialKind.ENUM -> aliases[serialKey(descriptor)] ?: "unknown"
            StructureKind.CLASS, StructureKind.OBJECT -> {
                if (descriptor.isInline && descriptor.elementsCount == 1) {
                    tsType(descriptor.getElementDescriptor(0))
                } else {
                    aliases[serialKey(descriptor)] ?: "unknown"
                }
            }
            else -> "unknown"
        }
        return if (descriptor.isNullable) "$inner | null" else inner
    }
}

private fun serialKey(descriptor: SerialDescriptor): String =
    descriptor.serialName.removeSuffix("?")

private fun simpleName(serialName: String): String {
    val trimmed = serialName.substringBefore('<').substringAfterLast('.')
    return trimmed.ifBlank { "Anonymous" }
}

private fun isKotlinBuiltin(serialName: String): Boolean =
    serialName.startsWith("kotlin.") || serialName.startsWith("kotlinx.serialization.")

private fun pageIdName(pagesName: String): String =
    if (pagesName.endsWith("Pages")) pagesName.removeSuffix("Pages").ifBlank { "" } + "PageId"
    else pagesName + "Id"

private fun actionsName(pagesName: String): String =
    if (pagesName.endsWith("Pages")) pagesName.removeSuffix("Pages").ifBlank { "" } + "Actions"
    else pagesName + "Actions"

private fun actionIdName(pagesName: String): String =
    if (pagesName.endsWith("Pages")) pagesName.removeSuffix("Pages").ifBlank { "" } + "ActionId"
    else pagesName + "ActionId"
