package dev.kolektiv.keel.typegen

import dev.kolektiv.keel.action.actions
import dev.kolektiv.keel.page.pages
import dev.kolektiv.keel.typegen.TypegenContract
import kotlinx.serialization.Serializable
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class TypegenTest {

    @Serializable
    enum class Kind { Note, Photo }

    @Serializable
    data class Child(val n: Int)

    @Serializable
    data class Payload(
        val tags: List<String>,
        val nested: List<List<Child>>,
        val note: String?,
        val kind: Kind,
        val extras: Map<String, Int>,
    )

    @Test
    fun `emits nested lists nullable and enum`() {
        val registry = pages {
            page<Payload>("demo.payload", "/demo")
        }
        val ts = Typegen.emit(registry)
        assertEquals(
            """
            // Generated by dev.kolektiv.keel.typegen.Typegen. Do not edit.

            export interface Child {
              n: number
            }

            export type Kind = "Note" | "Photo"

            export interface Payload {
              tags: string[]
              nested: Child[][]
              note: string | null
              kind: Kind
              extras: Record<string, number>
            }

            export interface Pages {
              "demo.payload": Payload
            }

            export type PageId = keyof Pages
            """.trimIndent() + "\n",
            ts,
        )
    }

    @Serializable
    data class PostSummary(val slug: String, val title: String)

    @Serializable
    data class HomePage(val kicker: String, val posts: List<PostSummary>)

    @Serializable
    data class NotFoundPage(val path: String, val title: String = "gone")

    @Test
    fun `pages map name is overridable`() {
        val registry = pages {
            page<HomePage>("harbor.home", "/")
            page<NotFoundPage>("harbor.notFound", "/__not-found")
        }
        val ts = Typegen.emit(registry, pagesName = "HarborPages")
        assertTrueContains(ts, "export interface HarborPages {")
        assertTrueContains(ts, "\"harbor.home\": HomePage")
        assertTrueContains(ts, "\"harbor.notFound\": NotFoundPage")
        assertTrueContains(ts, "export type HarborPageId = keyof HarborPages")
        assertTrueContains(ts, "export interface PostSummary {")
        assertTrueContains(ts, "posts: PostSummary[]")
        assertTrueContains(ts, "title: string")
        assertEquals(false, ts.contains("export interface HarborActions"), ts)
    }

    @Serializable
    data class SetNameIn(val displayName: String)

    @Serializable
    data class SetNameOut(val ok: Boolean)

    @Test
    fun `emits action in and out types`() {
        val registry = pages {
            page<HomePage>("harbor.home", "/")
        }
        val actions = actions {
            action<SetNameIn, SetNameOut>("harbor.setName")
        }
        val ts = Typegen.emit(registry, actions, pagesName = "HarborPages")
        assertTrueContains(ts, "export interface SetNameIn {")
        assertTrueContains(ts, "displayName: string")
        assertTrueContains(ts, "export interface SetNameOut {")
        assertTrueContains(ts, "ok: boolean")
        assertTrueContains(ts, "export interface HarborActions {")
        assertTrueContains(ts, "\"harbor.setName\": { in: SetNameIn; out: SetNameOut }")
        assertTrueContains(ts, "export type HarborActionId = keyof HarborActions")
    }

    @Test
    fun `json contract names page and action types`() {
        val registry = pages {
            page<HomePage>("harbor.home", "/")
        }
        val actions = actions {
            action<SetNameIn, SetNameOut>("harbor.setName")
        }
        val json = Typegen.emitJson(TypegenContract(registry.pages, actions.actions))
        assertTrueContains(json, "\"format\": \"keel/1\"")
        assertTrueContains(json, "\"harbor.home\"")
        assertTrueContains(json, "\"type\": \"HomePage\"")
        assertTrueContains(json, "\"path\": \"/\"")
        assertTrueContains(json, "\"GET\"")
        assertTrueContains(json, "\"harbor.setName\"")
        assertTrueContains(json, "\"in\": \"SetNameIn\"")
        assertTrueContains(json, "\"out\": \"SetNameOut\"")
        assertTrueContains(json, "\"types\"")
        assertTrueContains(json, "\"kicker\": \"string\"")
    }

    private fun assertTrueContains(haystack: String, needle: String) {
        assertEquals(true, haystack.contains(needle), "expected to contain:\n$needle\n\nin:\n$haystack")
    }
}
