// Generated by dev.kolektiv.keel.typegen.Typegen. Do not edit.

export interface UserRef {
  id: string
  displayName: string
}

export interface FeedItem {
  id: string
  userId: string
  displayName: string
  body: string
  at: string
}

export interface HomePage {
  viewer: UserRef | null
  feed: FeedItem[]
}

export interface NotFoundPage {
  path: string
  title: string
}

export interface UserPage {
  user: UserRef
  messages: FeedItem[]
}

export interface PostMessageIn {
  body: string
}

export interface PostMessageOut {
  message: FeedItem
}

export interface SetNameIn {
  displayName: string
}

export interface SetNameOut {
  user: UserRef
}

export interface HarborPages {
  "harbor.home": HomePage
  "harbor.notFound": NotFoundPage
  "harbor.user": UserPage
}

export type HarborPageId = keyof HarborPages

export interface HarborActions {
  "harbor.postMessage": { in: PostMessageIn; out: PostMessageOut }
  "harbor.setName": { in: SetNameIn; out: SetNameOut }
}

export type HarborActionId = keyof HarborActions
