import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { originFromHost, parsePackSchema, schemaUrl, type PackSchema, type SchemaType } from "./schema.ts"

export type ScaffoldFramework = "svelte" | "react"

export interface ScaffoldOptions {
  outDir: string
  origin?: string
  schema?: PackSchema
  schemaPath?: string
  framework?: ScaffoldFramework
  id?: string
  version?: string
  pagesName?: string
  force?: boolean
  fetchImpl?: typeof fetch
}

export async function loadSchema(options: ScaffoldOptions): Promise<PackSchema> {
  if (options.schema) return options.schema
  if (options.schemaPath) {
    const source = readFileSync(options.schemaPath, "utf8")
    return parsePackSchema(JSON.parse(source), options.schemaPath)
  }
  if (!options.origin) {
    throw new Error("keel-scaffold: pass an origin or --schema <file>")
  }
  const url = schemaUrl(options.origin)
  const fetchFn = options.fetchImpl ?? fetch
  const response = await fetchFn(url)
  if (!response.ok) {
    throw new Error(`keel-scaffold: GET ${url} failed (${response.status})`)
  }
  return parsePackSchema(await response.json(), url)
}

export async function scaffoldPack(options: ScaffoldOptions): Promise<string[]> {
  const framework = options.framework ?? "svelte"
  if (framework !== "svelte") {
    throw new Error(`keel-scaffold: framework '${framework}' is not generated yet; pass --framework svelte`)
  }
  const schema = await loadSchema(options)
  const pageIds = Object.keys(schema.pages)
  if (pageIds.length === 0) {
    throw new Error("keel-scaffold: schema has no pages")
  }
  const outDir = options.outDir
  mkdirSync(outDir, { recursive: true })
  const id = options.id ?? basenameId(outDir)
  const version = options.version ?? "0.1.0"
  const pagesName = options.pagesName ?? schema.pagesName ?? pascal(id) + "Pages"
  const notFound = pageIds.find((pageId) => pageId.endsWith(".notFound") || pageId === "not-found" || pageId === "notFound")
  const written: string[] = []

  write(outDir, "package.json", packageJson(id, version), options.force, written)
  write(outDir, "tsconfig.json", tsconfigJson(), options.force, written)
  write(outDir, "svelte.config.js", svelteConfig(), options.force, written)
  write(outDir, "vite.config.ts", viteConfig(id, version, notFound), options.force, written)
  write(outDir, "src/env.d.ts", envDts(), options.force, written)
  write(outDir, "src/bootstrap.ts", bootstrapTs(), options.force, written)
  write(outDir, "src/styles.css", stylesCss(), options.force, written)
  write(outDir, "src/lib/page-types.ts", emitTypescript(schema, pagesName), options.force, written)
  write(outDir, "src/lib/page-types.json", `${JSON.stringify(schema, null, 2)}\n`, options.force, written)
  write(outDir, "src/pages/+layout.svelte", rootLayout(), options.force, written)

  for (const pageId of pageIds) {
    const page = schema.pages[pageId]
    const dir = pageId.split(".").join("/")
    const depth = pageId.split(".").length
    const typesImport = `${"../".repeat(depth + 1)}lib/page-types`
    write(
      outDir,
      `src/pages/${dir}/+page.ts`,
      `export const id = ${JSON.stringify(pageId)}\n`,
      options.force,
      written,
    )
    write(
      outDir,
      `src/pages/${dir}/+page.svelte`,
      pageSvelte(pageId, page.type, page.path ?? "/", typesImport),
      options.force,
      written,
    )
  }
  return written
}

function write(root: string, relative: string, content: string, force: boolean | undefined, written: string[]): void {
  const file = join(root, relative)
  if (existsSync(file) && !force) {
    throw new Error(`keel-scaffold: ${relative} exists (pass --force to overwrite)`)
  }
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, content)
  written.push(relative)
}

function basenameId(outDir: string): string {
  const base = outDir.replace(/[\\/]+$/, "").split(/[\\/]/).pop() || "pack"
  return base.replace(/[^A-Za-z0-9._-]+/g, "-")
}

function pascal(value: string): string {
  return value
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("")
}

export function emitTypescript(schema: PackSchema, pagesName: string): string {
  const pageIdName = pagesName.endsWith("Pages")
    ? `${pagesName.slice(0, -5) || ""}PageId`
    : `${pagesName}Id`
  const actionsName = pagesName.endsWith("Pages")
    ? `${pagesName.slice(0, -5) || ""}Actions`
    : `${pagesName}Actions`
  const actionIdName = pagesName.endsWith("Pages")
    ? `${pagesName.slice(0, -5) || ""}ActionId`
    : `${pagesName}ActionId`
  const lines = ["// Generated by keel-scaffold from GET /__keel/schema. Do not edit.", ""]
  for (const [name, type] of Object.entries(schema.types ?? {})) {
    lines.push(...emitType(name, type), "")
  }
  lines.push(`export interface ${pagesName} {`)
  for (const [id, page] of Object.entries(schema.pages)) {
    lines.push(`  ${JSON.stringify(id)}: ${page.type}`)
  }
  lines.push("}", "", `export type ${pageIdName} = keyof ${pagesName}`)
  const actions = schema.actions ?? {}
  if (Object.keys(actions).length > 0) {
    lines.push("", `export interface ${actionsName} {`)
    for (const [id, action] of Object.entries(actions)) {
      lines.push(`  ${JSON.stringify(id)}: { in: ${action.in}; out: ${action.out} }`)
    }
    lines.push("}", "", `export type ${actionIdName} = keyof ${actionsName}`)
  }
  return `${lines.join("\n")}\n`
}

function emitType(name: string, type: SchemaType): string[] {
  if (type.kind === "enum" && type.values) {
    return [`export type ${name} = ${type.values.map((value) => JSON.stringify(value)).join(" | ")}`]
  }
  const fields = type.fields ?? {}
  const body = Object.entries(fields).map(([field, ts]) => `  ${field}: ${ts}`)
  return [`export interface ${name} {`, ...body, `}`]
}

function packageJson(id: string, version: string): string {
  return `${JSON.stringify(
    {
      name: id,
      private: true,
      version,
      type: "module",
      scripts: {
        dev: "vite build --watch",
        build: "vite build",
        typecheck: "tsc --noEmit -p tsconfig.json",
      },
      dependencies: {
        "@kolektiv/keel": "workspace:*",
        "@kolektiv/keel-svelte": "workspace:*",
        "@tanstack/query-core": "^5.66.0",
        "@tanstack/svelte-query": "^5.66.0",
        svelte: "^5.16.0",
      },
      devDependencies: {
        "@kolektiv/keel-pack": "workspace:*",
        "@sveltejs/vite-plugin-svelte": "^5.0.3",
        typescript: "^5.7.0",
        vite: "^6.2.0",
      },
    },
    null,
    2,
  )}\n`
}

function tsconfigJson(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        lib: ["ES2022", "DOM", "DOM.Iterable"],
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        isolatedModules: true,
        skipLibCheck: true,
        noEmit: true,
        verbatimModuleSyntax: true,
        types: ["vite/client"],
      },
      include: ["src/**/*.ts", "src/**/*.d.ts"],
    },
    null,
    2,
  )}\n`
}

function svelteConfig(): string {
  return `/** @type {import('@sveltejs/vite-plugin-svelte').Options} */
export default {
  compilerOptions: { runes: true },
  vitePlugin: {
    dynamicCompileOptions({ filename }) {
      if (filename.includes("node_modules")) return { runes: false }
    },
  },
}
`
}

function viteConfig(id: string, version: string, notFound: string | undefined): string {
  const notFoundLine = notFound ? `\n      notFound: ${JSON.stringify(notFound)},` : ""
  return `import { svelte } from "@sveltejs/vite-plugin-svelte"
import { keelPack } from "@kolektiv/keel-pack/vite"
import { defineConfig } from "vite"

export default defineConfig({
  plugins: [
    svelte(),
    keelPack({
      id: ${JSON.stringify(id)},
      version: ${JSON.stringify(version)},
      framework: "svelte",
      pagesDir: "src/pages",
      bootstrap: "src/bootstrap.ts",
      contract: "src/lib/page-types.json",${notFoundLine}
      pack: ${JSON.stringify(`dist/${id}.feb`)},
    }),
  ],
})
`
}

function envDts(): string {
  return `declare module "*.svelte" {
  import type { Component } from "svelte"
  const component: Component
  export default component
}

declare module "*.css" {
  const css: string
  export default css
}
`
}

function bootstrapTs(): string {
  return `import { bootstrap } from "@kolektiv/keel-svelte"

void bootstrap()
`
}

function stylesCss(): string {
  return `:root {
  color-scheme: dark;
  font-family: "Source Sans 3", "Segoe UI", system-ui, sans-serif;
  background: #1e1e2e;
  color: #cdd6f4;
}
html, body { margin: 0; min-height: 100%; }
.shell { max-width: 42rem; margin: 0 auto; padding: 2rem 1.25rem 4rem; }
.lede { color: #a6adc8; }
pre { overflow: auto; background: #181825; padding: 1rem; border-radius: 0.5rem; }
`
}

function rootLayout(): string {
  return `<script lang="ts">
  import type { Snippet } from "svelte"
  import "../styles.css"

  let { children }: { children: Snippet } = $props()
</script>

<div class="shell">
  {@render children()}
</div>
`
}

function pageSvelte(id: string, typeName: string, path: string, typesImport: string): string {
  return `<script lang="ts">
  import { Head, page } from "@kolektiv/keel-svelte"
  import type { ${typeName} } from "${typesImport}"

  const ctx = page<${typeName}>()
</script>

<Head />

<p class="lede">${id} · <code>${path}</code></p>
<pre>{JSON.stringify(ctx.data, null, 2)}</pre>
`
}

export { originFromHost, schemaUrl }
